Repository pypa/packaging.python.org, pull requests merged in 2021-12, with the labels that each got.

#1014 Make translation strings collection workflow use a dedicated branch
  .github/workflows/translation.yml
  locales/messages.pot
Labels: bug, enhancement

#1021 Fix branch variable name in translation workflow
  .github/workflows/translation.yml
Labels: bug, help wanted

#1033 Upgrade expected Python version
  source/contribute.rst
Labels: enhancement
