Repository pypa/packaging.python.org, pull requests merged in 2021-02, with the labels that each got.

#820 Replace Travis CI with GitHub Actions
  .github/workflows/test.yml
  .travis.yml
Labels: administrivia, enhancement

#834 Update link to setuptools doc
  source/guides/distributing-packages-using-setuptools.rst
Labels: enhancement

#835 Update setuptools link
  source/guides/distributing-packages-using-setuptools.rst
Labels: enhancement

#826 feat: add project_urls example
  source/tutorials/packaging-projects.rst
Labels: enhancement

#837 Recommend twine check to check long description
  source/conf.py
  source/guides/distributing-packages-using-setuptools.rst
Labels: enhancement

#842 Merge PR #840 and PR #841' into main
  source/tutorials/packaging-projects.rst
Labels: bug
