Repository pypa/packaging.python.org, pull requests merged in 2023-12, with the labels that each got.

#1418 Improve discussion "Is `setup.py` deprecated?"
  source/discussions/setup-py-deprecated.rst
Labels: diataxis: explanation

#1423 DOC: Document RECORD modification
  source/specifications/recording-installed-packages.rst
Labels: diataxis: reference

#1426 Add discussion "Distribution package vs. import package"
  source/discussions/distribution-package-vs-import-package.rst
  source/discussions/index.rst
  source/glossary.rst
  source/guides/packaging-namespace-packages.rst
Labels: diataxis: explanation

#1475 🧪🔧 Move cron trigger to separate GHA workflow
  .github/workflows/cron.yml
  .github/workflows/test.yml
Labels: type: task
